title: Daily Report

repository: akameco/daily-report
baseurl: /daily-report

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

timezone: Asia/Tokyo
future: true
paginate: 3
