title: Daily Report

repository: akameco/daily-report
baseurl: /daily-report

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock

timezone: Asia/Tokyo
future: true
